version: '3.3'
services:
    # lb : 
    #   build : ./lb
    #   ports : 
    #     - "7000:80"
    app1: 
      build: ./service1
      ports:
        - "3001:8008"

    app2 :
      build : ./service2
      ports :
        - "3002:8009"
    redis :
      image: redis
     
      