version: '3.3'
services:
    lb : 
      build : ./lb
      ports : 
        - "7000:80"
    app1: 
      build: ./service1
      ports:
        - "5001:8008"

    app2 :
      build : ./service2
      ports :
        - "5002:8009"

