version: '3.3'
services:
    lb: 
     build : ./lb
     ports : 
        - "8000:80"
    app1: 
      build: ./service1
      ports:
        - "8008:5000"

    app2 :
      build : ./service2
      ports :
        - "8009:5000"

    redis :
     image : redis
